### ISSUE TITLE
Problem with .pyt Toolbox

### ISSUE THREAD

**Issue by ongaro1** [NASA-DEVELOP/METRIC#1]
In Arcmap 10.1 I load the .pyt toolbox, but the two scripts don't run. The error message is blunt ("Unable to execute the selected tool", and that's all...).
From IDLE, the scripts run with no errors - obviously, also no output.

**Comment by ongaro1** [comment]
Solved. My fault.
I was using an Arcmap 10.1 without SP. In the out-of-the-box version Datatype keywords are not defined (getParameterInfo method). Installing SP1 solved the problem.

**Comment by Jwely** [comment]
Great! I thought that might have been the case, but without an Arcmap system to test it out on I couldn't troubleshoot.

**Comment by ongaro1** [comment]
I'm a QGIS adept, not so familiar with ESRI... Any project to port METRIC into QGIS?

**Comment by Jwely** [comment]
The functionality could be completely replicated for use in QGIS with extensive use of GDAL, but no port efforts are currently under way.
