### ISSUE TITLE
Cannot create a valid config file

### ISSUE THREAD

**Issue by ongaro1** [NASA-DEVELOP/METRIC#2]
I am not able to create a valid configuration file using METRIC_configure.
Many annoying issues occur (.ovr and .xml are required, shapefile codepage etc.). 
The bad point is that Landsat band 2 seems to be skipped (wrong enumeration?)... 
Do you have a working config file, just to check its format and/or try a manual config?

**Comment by ongaro1** [comment]
So far, it seems that there are some bugs in METRIC_configure that I am not interested in fixing.
But manually hacking the configuration file I got the model running properly. 
What a great job you did, guys.

**Comment by sajjad2923** [comment]
I am also facing problems related to configuration files. The METRIC model is integrated into GSI 10.5. The first step to making the configuration folder is done but unfortunately, I am unable to run that configuration folder in the 2nd step of METRIC model. so if you are able to answer the problem please let me know about it. 
Regards.
