### ISSUE TITLE
no output directory or existing OVR check in place

### ISSUE THREAD

**Issue by lsapia** [NASA-DEVELOP/METRIC#3]
Hi all,
i'm an italian engineer. I have studied the METRIC model for the estimation of actual evapotranspiration from satellite images.
I found on github your model (NASA-DEVELOP/METRIC) and i'm trying to make it work on Northern Italy, but it doesn't work. I can't understand why...
Can you help me?
I'm attaching the input dialog box and error message printed in Executing METRIC_configure in ArcGIS 10.2.2:

![input dialog box](https://cloud.githubusercontent.com/assets/18532586/14606485/bdb6715a-057d-11e6-83d7-912f2e5eb2d7.PNG)
![error message](https://cloud.githubusercontent.com/assets/18532586/14606486/bdd04b7a-057d-11e6-884b-89c08b46511d.PNG)

Thank you for your attention,
Luca

**Comment by lsapia** [comment]
Sorry this is the complete input dialog box:
![input dialog box_correct](https://cloud.githubusercontent.com/assets/18532586/14606931/b64d0af8-057f-11e6-9d1c-9e10cabc06ac.PNG)

**Comment by Jwely** [comment]
Can you confirm that your selected output directory `C:\users\lsapia\desktop\2016_LET\temp_METRIC\output` does not already exist?

**Comment by lsapia** [comment]
Ah ok it must be a completely NEW directory! I changed the filepath for output into: 

C:\users\lsapia\desktop\2016_LET\temp_METRIC\outputs (a directory that not already exist)

but now there is the new following error message:

![error message_2](https://cloud.githubusercontent.com/assets/18532586/14620260/06a190fa-05bc-11e6-9616-2cd4e5426828.PNG)

this is the input dialog box:

![input dialog_2_1](https://cloud.githubusercontent.com/assets/18532586/14620376/928ba786-05bc-11e6-9bd7-f762db8e830d.PNG)
![input dialog_2_2](https://cloud.githubusercontent.com/assets/18532586/14620380/95237e10-05bc-11e6-9a51-b7ede3f23a62.PNG)

(this evening i'm trying with a ArcMap 10.3, i don't know if something can change)

**Comment by Jwely** [comment]
For some reason the setup copys OVR files without checking that they exist.

an attempted fix has been created on the `patch-ovr-issue` branch which you can download [here](https://github.com/NASA-DEVELOP/METRIC/archive/patch-ovr-issue.zip).

please give this a try, and if it works ill merge the branch and close the issue.

**Comment by lsapia** [comment]
i think that we need something similar even for dem.tif image:

![error message dem](https://cloud.githubusercontent.com/assets/18532586/14621186/5e2b226e-05c1-11e6-94ca-adcf292b67cc.PNG)

thanks

**Comment by Jwely** [comment]
I made some additional changes. Sadly I am no longer on an arcmap system where I can test these fixes myself so there may be a bit of back-and-forth on this.

I've made additional changes to the patch-ovr branch, [here](https://github.com/NASA-DEVELOP/METRIC/archive/patch-ovr-issue.zip)

**Comment by lsapia** [comment]
Unfortunately there is still one error :( 

![error_5](https://cloud.githubusercontent.com/assets/18532586/14621666/c1529d88-05c4-11e6-8144-4d2f4e391668.PNG)

**Comment by Jwely** [comment]
Updated once more.

[download](https://github.com/NASA-DEVELOP/METRIC/archive/patch-ovr-issue.zip)

**Comment by lsapia** [comment]
After 19 minutes and 52 seconds (when i finally hoped that it had worked) one error message again:

![error_6](https://cloud.githubusercontent.com/assets/18532586/14650244/361ad5c6-066b-11e6-8425-0401255bd6cd.PNG)

**Comment by lsapia** [comment]
Hello Jeff, when you have a little time please help me to solve this final (i hope) issue.
Thanks for doing a lot of work really useful to users! :)

**Comment by Jwely** [comment]
This is a different issue than the original one, so I'm creating a new issue at #5 and marking this one as resolved.
